export const dataSource = [
  {
    key: "1",
    image:
      "https://img.lazcdn.com/g/p/2daa1b86ddd55bacf31c8836c75f0a07.jpg_720x720q80.jpg",
    itemCode: "ITM001",
    itemName: "Item Name 1",
    category: "Category A",
    quantity: 100,
    price: "$10.00",
    supplier: "Supplier X",
    lastUpdated: "2024-01-01",
  },
  {
    key: "2",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmZwvt0iUvgrX-J0-d4gxpsLIhyL2aFcq7Qw&s",
    itemCode: "ITM002",
    itemName: "Item Name 2",
    category: "Category B",
    quantity: 50,
    price: "$20.00",
    supplier: "Supplier Y",
    lastUpdated: "2024-01-05",
  },
  {
    key: "3",
    image: "https://inwfile.com/s-cj/8c7rce.jpg",
    itemCode: "ITM003",
    itemName: "Item Name 3",
    category: "Category A",
    quantity: 75,
    price: "$15.00",
    supplier: "Supplier Z",
    lastUpdated: "2024-01-10",
  },
  {
    key: "4",
    image: "https://inwfile.com/s-cm/nrgxc6.jpg",
    itemCode: "ITM004",
    itemName: "Item Name 4",
    category: "Category A",
    quantity: 75,
    price: "$15.00",
    supplier: "Supplier Z",
    lastUpdated: "2024-01-10",
  },
  {
    key: "5",
    image:
      "https://hovbbkidsclub.com/wp-content/uploads/2025/03/FG-144_Hovbb-Kids-Club-Soft-Play-Climbing-Playpen-Playset-Gym-School-Cafe-Nursary_1.webp",
    itemCode: "ITM005",
    itemName: "Item Name 5",
    category: "Category A",
    quantity: 75,
    price: "$15.00",
    supplier: "Supplier Z",
    lastUpdated: "2024-01-10",
  },
];
