export const stockDataSource = [
  {
    key: "1",
    itemImage: null,
    itemCode: "ITM001",
    itemName: "Item Name 1",
    category: "Category A",
    quantity: 100,
    price: "10.00",
    supplier: "Supplier X",
    lastUpdated: "2024-01-01",
  },
  {
    key: "2",
    itemImage: null,
    itemCode: "ITM002",
    itemName: "Item Name 2",
    category: "Category B",
    quantity: 50,
    price: "20.00",
    supplier: "Supplier Y",
    lastUpdated: "2024-01-05",
  },
  {
    key: "3",
    itemImage: null,
    itemCode: "ITM003",
    itemName: "Item Name 3",
    category: "Category A",
    quantity: 75,
    price: "15.00",
    supplier: "Supplier Z",
    lastUpdated: "2024-01-10",
  },
  {
    key: "4",
    itemImage: null,
    itemCode: "ITM004",
    itemName: "Item Name 4",
    category: "Category A",
    quantity: 75,
    price: "15.00",
    supplier: "Supplier Z",
    lastUpdated: "2024-01-10",
  },
  {
    key: "5",
    itemImage: null,
    itemCode: "ITM005",
    itemName: "Item Name 5",
    category: "Category A",
    quantity: 75,
    price: "15.00",
    supplier: "Supplier Z",
    lastUpdated: "2024-01-10",
  },
];

export const orderDataSource = [
  {
    key: "1",
    orderDate: "2024-01-01",
    cvCode: "ITM001",
    cvDesc: "ITM001",
    itemCode: "Item Name 1",
    itemName: "Item Name 1",
    category: "Category A",
    quantity: 100,
    totalAmount: "10.00",
  },
];
